services:
    db:
        image: postgres:17.5
        ports: 
            - 5432:5432
        environment:
            - POSTGRES_USER=petclinic
            - POSTGRES_PASSWORD=petclinic
            - POSTGRES_DB=petclinic
        container_name: postgres_DB
        volumes:
            - postgres_data:/var/lib/postgresql/data

    web:
        image: spring-petclinic:latest
        container_name: postgres_front_app
        depends_on:
            - db
        ports:
            - 8081:8080
        environment:    
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_DB:5432/petclinic
            - SPRING_DATASOURCE_USERNAME=petclinic
            - SPRING_DATASOURCE_PASSWORD=petclinic
            - SPRING_PROFILES_ACTIVE=postgres 
volumes:
    postgres_data:
# docker run -e POSTGRES_USER=petclinic -e POSTGRES_PASSWORD=petclinic -e POSTGRES_DB=petclinic -p 5432:5432 postgres:17.5

