services:
    db:
        image: postgres:17.5
        ports: 
            - 5432:5432
        environment:
            - POSTGRES_USER=petclinic
            - POSTGRES_PASSWORD=petclinic
            - POSTGRES_DB=root
            - MYSQL_DATABASE=petclinic
        container_name: postgres_DB
    web:
        image: spring-petclinic:latest
        container_name: postgres_front_app
        depends_on:
            - db
        ports:
          - 8081:8080

# docker run -e POSTGRES_USER=petclinic -e POSTGRES_PASSWORD=petclinic -e POSTGRES_DB=petclinic -p 5432:5432 postgres:17.5

